# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  WSO2 CICD Pipe line
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Cluster Configuration
        Parameters:
          - AWSAccessKeyId
          - AWSAccessKeySecret
          - KeyPairName
          - WSO2InstanceType
      - Label:
          default: Network Configuration
        Parameters:
          - CertificateName
      - Label:
          default: Database Configuration
        Parameters:
          - DBUsername
          - DBPassword
          - DBType
      - Label:
          default: WSO2 Credentials
        Parameters:
          - WUMUsername
          - WUMPassword
      - Label:
          default: GitHub Credentials
        Parameters:
          - GitHubUsername
          - GitHubPassword
          - GitHubHookRepository
      - Label:
          default: Product Configuration
        Parameters:
          - ProductName
          - DeploymentPattern
      - Label:
          default: Other Parameters
        Parameters:
          - GITREPOARTIFACTS
          - GITREPOCF
          - GITREPOPUPPET
          - Email
    ParameterLabels:
      AWSAccessKeyId:
        default: AWS Access Key ID
      AWSAccessKeySecret:
        default: AWS Access Secret Key
      CertificateName:
        default: SSL Certificate Name
      KeyPairName:
        default: Key Pair Name
      GitHubUsername:
        default: Username
      GitHubPassword:
        default: Password
      GitHubHookRepository:
        default: Git Hook Repository Name
      WUMUsername:
        Default: Username
      WUMPassword:
        Default: Password
      WSO2InstanceType:
        default: Instance Type
      DBUsername:
        default: Username
      DBPassword:
        default: Password
      DBType:
        default: Database Type
      GITREPOARTIFACTS:
        default: Artifacts Repository (git)
      GITREPOCF:
        default: CloudFormation Scripts (git)
      GITREPOPUPPET:
        default: Configuration Repository (git)
      ProductName:
        default: Product Name
      DeploymentPattern:
        default: Product Deployment Pattern
      Email:
        default: Email
Parameters:
  AWSAccessKeyId:
    Type: String
  AWSAccessKeySecret:
    Type: String
  KeyPairName:
    Description: The private key used to log in to instances through SSH
    Type: 'AWS::EC2::KeyPair::KeyName'
  CertificateName:
    Description: A valid SSL certificate used for HTTPS
    Type: String
  WSO2InstanceType:
    Type: String
    Default: t2.medium
    AllowedValues:
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
    ConstraintDescription: Must be a valid EC2 instance type
  ProductName:
    Type: String
    AllowedValues:
      - wso2ei
      - wso2is
  DeploymentPattern:
    Type: String
    AllowedValues:
      - ei_integrator
      - is
  GitHubUsername:
    Type: String
    Default: ""
  GitHubPassword:
    Type: String
    Default: ""
    NoEcho: true
  GitHubHookRepository:
    Type: String
    Default: ""
  WUMUsername:
    Type: String
    Default: ""
  WUMPassword:
    Type: String
    Default: ""
    NoEcho: true
  DBUsername:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBType:
    Type: String
    Default: MySQL
  GITREPOARTIFACTS:
    Default: https://github.com/wso2-incubator/cicd-test-artifacts.git
    Type: String
  GITREPOCF:
    Default: https://github.com/wso2-incubator/cicd-deployment-scripts.git
    Type: String
  GITREPOPUPPET:
    Type: String
  Email:
    Description: A valid email address to receive notifications on pipeline
    Type: String
Resources:
  # networking configurations
  WSO2EIPublicInternetGateway:
    Type: 'AWS::EC2::InternetGateway'

  WSO2EIPublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref TESTVPC

  WSO2EIPublicSubnet1RouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref WSO2EIPublicRouteTable
      SubnetId: !Ref TestSubnet1

  WSO2EIPublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref WSO2EIPublicRouteTable
      GatewayId: !Ref WSO2EIPublicInternetGateway
      DestinationCidrBlock: 0.0.0.0/0
    DependsOn: WSO2EIVPCInternetGatewayAttachment

  WSO2EIVPCInternetGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref WSO2EIPublicInternetGateway
      VpcId: !Ref TESTVPC
  WSO2JenkinsInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      DisableApiTermination: 'false'
      InstanceInitiatedShutdownBehavior: stop
      ImageId: !FindInMap
        - WSO2UbuntuAMIRegionMap
        - !Ref 'AWS::Region'
        - !Ref ProductName
      InstanceType: t2.medium
      KeyName: !Ref KeyPairName
      Monitoring: 'false'
      Tags:
        - Key: Name
          Value: WSO2JenkinsInstance
      NetworkInterfaces:
        - DeleteOnTermination: 'true'
          AssociatePublicIpAddress : 'true'
          Description: Primary network interface
          DeviceIndex: 0
          SubnetId: !Ref TestSubnet1
          GroupSet:
            - !Ref JenkinsSecurityGroup
      UserData: !Base64
        'Fn::Sub': |
          #cloud-boothook
          #!/bin/bash
          export PATH=~/.local/bin:$PATH
          sed -i "s|VAL1|${GITREPOARTIFACTS}|g" /home/jenkins/jenkins_env
          sed -i "s|VAL2|${GITREPOCF}|g" /home/jenkins/jenkins_env
          sed -i "s|VAL3|${GITREPOPUPPET}|g" /home/jenkins/jenkins_env
          sed -i "s/VAL4/${KeyPairName}/g" /home/jenkins/jenkins_env
          sed -i "s/VAL5/${WSO2InstanceType}/g" /home/jenkins/jenkins_env
          sed -i "s/VAL6/${CertificateName}/g" /home/jenkins/jenkins_env
          sed -i "s/VAL7/${DBUsername}/g" /home/jenkins/jenkins_env
          sed -i "s/VAL8/${DBPassword}/g" /home/jenkins/jenkins_env
          sed -i "s/VAL9/${DBType}/g" /home/jenkins/jenkins_env
          sed -i "s/VALX/${ProductName}/g" /home/jenkins/jenkins_env
          sed -i "s/VALY/${DeploymentPattern}/g" /home/jenkins/jenkins_env
          sed -i "s/VALZ/${Email}/g" /home/jenkins/jenkins_env
          sed -i "s/VAL1/${AWSAccessKeyId}/g" /home/ubuntu/.aws/credentials
          sed -i "s|VAL2|${AWSAccessKeySecret}|g" /home/ubuntu/.aws/credentials
          sed -i "s/VAL1/${AWS::Region}/g" /home/ubuntu/.aws/config

          export publichostname=$(ec2metadata --public-hostname)
          sed -i "s/VAL/$publichostname/g" /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml
          service jenkins start

          export jenkinshookurl=http://$publichostname:8080/github-webhook/
          export githubhookurl=https://api.github.com/repos/${GitHubUsername}/${GitHubHookRepository}/hooks
          sleep 60 # wait for 1 of the second before check again
          export JENKINS_CRUMB=$(curl -s 'http://admin:admin@localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
          echo $JENKINS_CRUMB >> /home/ubuntu/log.txt
          curl -s -X POST -H $JENKINS_CRUMB 'http://admin:admin@localhost:8080/credentials/store/system/domain/_/createCredentials' --data-urlencode 'json={"": "0","credentials":{"scope":"GLOBAL","id":"wum_creds","username":"${WUMUsername}","password": "${WUMPassword}","description": "WUM Credentials","$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"}}' -v >> /home/ubuntu/text.txt
          curl -s -X POST -H $JENKINS_CRUMB 'http://admin:admin@localhost:8080/credentials/store/system/domain/_/createCredentials' --data-urlencode 'json={"": "0","credentials":{"scope":"GLOBAL","id":"aws_creds","accessKey":"${AWSAccessKeyId}","secretKey": "${AWSAccessKeySecret}","description": "AWS Credentials","$class": "com.cloudbees.jenkins.plugins.awscredentials.AWSCredentialsImpl"}}' -v >> /home/ubuntu/text.txt
          bash /home/jenkins/webhook/create_webhook.sh ${GitHubUsername} ${GitHubPassword} $githubhookurl $jenkinshookurl

  JenkinsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref TESTVPC
      GroupDescription: WSO2 Jenkins node Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
  TESTVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
  TestSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref TESTVPC
      CidrBlock: 10.0.254.0/24
      AvailabilityZone: !Select
        - '0'
        - !GetAZs ''
Outputs:
  JenkinsManagementConsoleURL:
    Value: !Sub '${WSO2JenkinsInstance.PublicDnsName}:8080/'
    Description: Jenkins Management Console URL
Mappings:
  WSO2UbuntuAMIRegionMap:
    us-east-1:
      wso2ei: ami-06ddc29690248d464
      wso2is: ami-023431dce70def62e
    us-east-2:
      wso2ei: ami-0149eccc437898f9c
      wso2is: ami-045714ca17bafaa2f
